debug.dump_rom_task(): Added ROM2.BIN for 550D. Moved out of #if CONFIG_DEBUGMSG because of vram.c:(.text+0xf8): undefined reference to `menu_draw_icon' debug.o:(.data+0xfc): undefined reference to `bmp_draw_palette'
hg-changeset: 7c3a687b0097de2503f1c14a0e13262c974d4461
hg-branch: unified